### ISSUE TITLE
Move stTransactionTest.ValueOverflow to transaction tests

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#1029]
https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stTransactionTest/ValueOverflow.json

Nothing executes in this test because the transaction is rejected at the RLP decoding phase. It should be more suitable for transaction tests.

Moreover, this is the only test containing undocumented prefix `0x:bigint `.

**Comment by winsvega** [comment]
this is a test. `0x:bigint` prefix basically disables structure field checks and allows to encode any value into the rlp. 
geth btw failed on calculating the balance, not decoding rlp. 
since Transaction tests are neglected by most of the teams I was thinking to add more this invalid RLP generations to State/Blockchain tests and see how clients behave on Hive.

**Comment by chfast** [comment]
Ok, so maybe convert Transaction tests to Blockchain tests?

I'm not convinced these tests will be particularly good. Because they will test JSON → internal transaction representation transition instead of intended RLP → internal transaction representation.

**Comment by winsvega** [comment]
testers are supposed to parse txbytes now in state tests. 
all state tests are converted to blockchain to be executed on hive. 
the evm t8n tool protocol parses the RLP

this test is PoC example because I am not convinced that devs run ttTransaction tests properly.

**Comment by winsvega** [comment]
This test actually helped us to discover a bug in the evm t8n accounts touch
