### ISSUE TITLE
retesteth does not produce vm trace for some `ValidBlock` tests

### ISSUE THREAD

**Issue by gurukamath** [ethereum/tests#1078]
I came across a handful of tests within the `ValidBlocks` folder that do not produce an evm trace with retesteth. I presume this is because these tests have invalid blocks in them. Is there any way of identifying such tests without running them through geth?

Also would it be more appropriate to have those tests in `InvalidBlocks`?

Example - [test](https://github.com/ethereum/tests/blob/develop/BlockchainTests/ValidBlocks/bcMultiChainTest/ChainAtoChainB.json) for the Berlin hard fork

**Comment by winsvega** [comment]
in that test trace is not retrived because imported block does not belong to the TOP difficulty chain, therefor thransaction is not found in the latest block. 

actually vmtrace in blockchain tests not tested. it is implemented but never tested. see if other cases work. 

I think I can fix it to look up for transaction in all known chains and print the vmtrace anyway. but does it make sense if chainreorg does no longer happen after Merge

**Comment by winsvega** [comment]
added more debug support for blockchain tests
including intermidiate statediffs and vmtrace for a specific transaction

https://ethereum-tests.readthedocs.io/en/latest/retesteth-ref.html#blockchain-test-debugging
