### ISSUE TITLE
GeneralStateTests.stackLimitPush31_1025 should expect the transaction to fail

### ISSUE THREAD

**Issue by xinifinity** [ethereum/tests#1086]
In the [stackLimitPush31_1025](https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stMemoryTest/stackLimitPush31_1025Filler.json) test, IIUC its intention is to check when reaching stack depth limit, which should be 1024, the transaction will fail with stack overflow error. However in the [expect](https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stMemoryTest/stackLimitPush31_1025Filler.json#L29) section, it expects the nonce of the account to increase even the transaction should fail, why is it the case?

**Comment by jochem-brouwer** [comment]
The transaction will fail because of a stack overflow error. However, the transaction will still succeed and will be logged (the nonce will be increased). Otherwise, it would be possible to "conditionally" send transactions: if X happens then stack overflow and the tx did not happen, but if Y happen execute the transaction. 

This is the same as if a transaction goes OOG. You sign a transaction, it should execute, and once it is executed it should be logged. If the EOA (externally owned account) wishes to execute it again, then resign the transaction with another nonce.

(This is all part of replay protection). So, this is not a bug (someone else confirm this please).

**Comment by holiman** [comment]
> someone else confirm this please

U got this :)

**Comment by xinifinity** [comment]
Makes sense, thanks a lot for the explanation!
