### ISSUE TITLE
Transcript invalid blocks in blockchain tests

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#1293]
evmone does not support rlp. Maybe some others too.

The current blockchain tests that have invalid blocks describe invalid block as rlp field only. And valid block as rlp and its json decoding into transactions, blockheader, etc.

Since long time tests now have expected exceptions, and all invalid rlp tests are moved to rlp tests.
So the invalid blocks must be valid rlps just expected to be rejected.

Proposal is to parse block from test as invalid if it has expected exception other then that invalid block will have all the same fields in tests as a valid one.

Affected: custom test runner tools
Backwards compatibility: legacy tests will break.

Question to the teams is this easy to implement in tools, is it ok? Some code might be hardcoded to expect rlp section only. 

Alternatively can have invalid blocks transcripted but in a different way than valid. Putting the json transcription into sub json section for instance.

**Comment by holiman** [comment]
> evmone does not support rlp. Maybe some others too.

It is not possible for an ethereum mainnet EL client to not support rlp. Since evmone implements only the evm-part, they may pull it off, but it's definitely the odd one out. 

> all invalid rlp tests are moved to rlp tests.

That is good, because testing valid/invalid rlp is a much simpler proposition than testing validity of blocks. 

>  So the invalid blocks must be valid rlps just expected to be rejected.

Right. Yes, definitely, exactly like If we were to describe them in `json`, then we'd have to use valid `json`. 

> Proposal is to parse block from test as invalid if it has expected exception other then that invalid block will have all the same fields in tests as a valid one.

Please clarify the proposal. Here is how I read it: 

> If the test has an `expected exception` field, then the block is supposed to be found `invalid`.

But I must be missing something, what am I missing?

**Comment by shemnon** [comment]
Besu has their EVM code in a severable library, but our reference test code is still part of the whole ethereum client.  This is because some of the tests, as mentioned, depend on things like RLP and block validation which are not EVM concerns but block building concerns.

It would be nice if there was a clear subsection of the code that was RLP and block free (GeneralStateTests is mostly there, if not completely) but I don't see Besu ever not running full block tests, and that makes block free testing moot.  So I would say Besu is neither in favor nor opposed to removing rlp from regular tests.

**Comment by winsvega** [comment]
Rlp is not removed. It's an issue of parsing by the test runners.

Old legacytests remain having only rlp field for invalid blocks.
And rlp + json for valid.

New proposal:
`exception + rlp + json` for invalid blocks.
`No exception + rlp + json` for valid blocks.

Because there are many test runner tools I never change filled test format severely so not to break things.

**Comment by winsvega** [comment]
> Please clarify the proposal. Here is how I read it: 
> 
> > If the test has an `expected exception` field, then the block is supposed to be found `invalid`.
> 
> But I must be missing something, what am I missing?
>  
> 
> 

You got it right. 
You missing that legacy tests will remain with rlp only for invalid blocks. And that introduction of json fields for invalid blocks might break the test runners that don't expect it there for invalid blocks and ignore expected exception field.

**Comment by jangko** [comment]
It will break nimbus-eth1 test, but it's easy to fix.

**Comment by winsvega** [comment]
Here is another option. That should be backwards compatible 

```
"rlp" : "0xf...",
"rlp_decoded" : {
    "blockheader",
    "transactions",
    ...
}
```

For invalid blocks. For valid no change.

**Comment by holiman** [comment]
I think the proposal should not be problematic to implement, for geth, however I do think it will lead to more problems. Decoding an rlp block is very simple, whereas decoding a `json`-structure into a block can be very ambiguous. 

A field missing from `json` can be interpreteted as `0`, in the case of `int` types. To clarify: For go-lang, a field defined as a non-pointer type is default initialized to the zero value, `0` for integers. In order to handle the case that something is not present, we need to know that beforehand and define it as an int-pointer. Therefore, say you want to create an "invalid" block that is missing a timestamp field in the header. In `rlp`, you would omit one of the fields, the field that representts the timestamp. In `json`, if you omit it, clients can choose wheher to implicitly assign it or not. 

Similarly, if you want to add an extra field (perhaps an upcoming field, such as the beaconroot).  In `rlp`, you just shove it into the rlp-stream and bob's your uncle. In `json`, you'd add a `beacon_root` or whatever to the struct. Now, in go-lang, extraneous fields that are not defined are just ignored. So if geth is not defined to know that there exists a field called `beacon_root`, it will just not care about it.

**Comment by winsvega** [comment]
You totally missing the point.
Rlp does not go anywhere. It remains there for invalid blocks.
How evmone going to construct blocks from json is their problem. Ideally you just ignore json representation of it, as you do for valid blocks. Just that the defenition of invalid block in blockchain test may conflict with the defenition of valid block if it also will have the json transcript. 

Json representation is there for the user btw, not to construct blocks from it. Hive works with rlps.

Btw invalid header you describe is more of a structure test than a blockchain. Like we have in transaction tests.

**Comment by holiman** [comment]
Alright, well if the json is only there for decoration, then sure, not a problem for us

**Comment by winsvega** [comment]
ok this is my idea so far: 


**Invalid blocks:**
```
"rlp" : "0xf...",
"rlp_decoded" : {
    "blockheader",
    "transactions",
    ...
}
```

**Valid blocks:**
```
"rlp" : "0xf...",
"blockheader" : { ... },
"transactions" : { ... },
 ...
}
```

**Comment by winsvega** [comment]
implemented https://github.com/ethereum/tests/blob/develop/BlockchainTests/InvalidBlocks/bcUncleHeaderValidity/gasLimitTooLow.json#L97
