### ISSUE TITLE
Add a test case to see if EIP-155 style transactions are refused before Spurious Dragon

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#233]
As noticed in https://github.com/ethereum/cpp-ethereum/pull/4255#issuecomment-315207079, no tests break when cpp-ethereum stops accepting EIP-155-style transactions before Spurious Dragon.  There should be test cases that try the clients on EIP-155-style transactions before Spurious Dragon.

**Comment by winsvega** [comment]
this test cases should be added as TransactionTests 
https://github.com/ethereum/tests/blob/develop/src/TransactionTestsFiller/Metropolis/ttTransactionTestFiller.json

the reason no test breaks is because transaction tests are not general transaction tests. 
each test case is run on a defined net rules only.

**Comment by winsvega** [comment]
We don't  have the tests in ttTransaction form. In fact those are quite unmaintained for a while now

**Comment by qbzzt** [comment]
> We don't have the tests in ttTransaction form. In fact those are quite unmaintained for a while now

Exactly. WE don't have ttTransaction tests, we don't care about life before Spurious Dragon, there is no reason to keep this issue.
