### ISSUE TITLE
Test missing for Internal Tx logs check if REVERT has been executed

### ISSUE THREAD

**Issue by mkalinin** [ethereum/tests#348]
A simple test case where Internal Tx executes `LOGN` and does `REVERT` after that. Maybe this is actual not only for Internal Txes.

**Comment by qbzzt** [comment]
Not so simple, because `LOG<n>` doesn't produce a clear trace that the EVM can see. We might be able to do this with a blockchain test that looks at the blockhash.

**Comment by winsvega** [comment]
in state tests there is loghash calculated for each transaction.

**Comment by qbzzt** [comment]
How do I check this loghash? I looked all over `tests/src`, and there is no `loghash` (or `logHash`) anywhere.

**Comment by qbzzt** [comment]
> Not so simple, because `LOG<n>` doesn't produce a clear trace that the EVM can see. We might be able to do this with a blockchain test that looks at the blockhash.

Doesn't work, because adding revert would be enough to change the state hash anyway. I am going to verify this behavior with `--poststate` and then check the block hash that has this behavior. If it changes, the block hash would change.

Note that other things, such as opcode repricing, can also change the block hash. I'll add a note how to update for that to the test.

**Comment by qbzzt** [comment]
#794 has this test, so I'm closing it.
