### ISSUE TITLE
Cutting off uninteresting test cases?

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#399]
This repository is getting bigger and bigger.

* do we want, at some point, to reduce contents of this repository?
* if yes, how do we choose which tests to keep and which to throw away?

**Comment by winsvega** [comment]
I suggest to compile tests only for those forks that are defined at expect section. 

So if there is an expect section for Metropolis. then the test is being generated on metropolis fork rules.
if there expect section saying ALL then it will be generated for all fork rules. 
transaction indexes should not count. 

This way we could specify on which forks to check the test and reduce the amount of tests.
This approach would require to review all of the tests however. 
Might be a good chance to add more comments to the test sources.

So for example static call tests does not have  to be executed on all forks. only starting from the point a static call is exist. We might need a new way to define expect section like   `>Metropolis ` means for all forks after metropolis. (although the gas price tend to change and it might be unreasonable. tell me what you think) 

A test that checks that staticcall is not executed before a certain point is a separate test case that should be compiled for all forks for all opcodes and check whether it works or not. @jwasinger  already done it for bad and correct opcodes. so it is done already. thus we do not need staticcall tests to be done on Frontier for example. (And we have like a hundred staticcall tests because it was merged blindly from all test cases that we had for existing call, delegate call scenarious)

**Comment by pirapira** [comment]
@chfast came up with one way to detect probably duplicate tests. Tests on different versions can be marked if they have the same input and the same post state hash.  I think that's a relatively safe way to cut down many tests.  With this, we can run more interesting tests on limited resources.

**Comment by winsvega** [comment]
so if test has the same results on fork1/fork2/fork3  
which version of the test should we keep? 
this is a tricky one. we could break something but on fork2 and not on fork3 and this test would work just fine but the client will stop syncing.

**Comment by pirapira** [comment]
@winsvega fork1.  It's better to break the sync at fork2 than fork1.

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/412
https://github.com/ethereum/tests/pull/413
https://github.com/ethereum/tests/pull/418
