### ISSUE TITLE
modulus of negative

### ISSUE THREAD

**Issue by romanman** [ethereum/tests#52]
(-5) mod 3 = 1

need to fix that: 

https://github.com/ethereum/tests/blob/develop/VMTests/vmArithmeticTest.json#L345

**Comment by CJentzsch** [comment]
No, its correct. Signed modulo is mathematically not defined. Python (and may be Java) compilers will give (-5) mod 3 = 1. C++ , Fortran, Go and some others will calculate (-5) mod 3 = 2. Since signed modulo is not defined and differs for every compiler, I defined it like the C style compilers. See YP: (-5) mod 3 = sgn(-5)*|-5| mod 3 = - (5 mod 3) = 2.

**Comment by romanman** [comment]
so you define it like this:

```
x mod y : if x < 0 and y >0  ==> -(|x| mod y)
              if x > 0 and y < 0  ==> -(x mod |y|)

```
how do you define: x mod y : x < 0  and y < 0 ?

**Comment by CJentzsch** [comment]
you take the absolute value of y. In the YP it says: µ[0] mod µ[1] = sgn(µ[0]) |µ[0]| mod |µ[1]| . And this always clearly defined.

**Comment by romanman** [comment]
got you thanks
