### ISSUE TITLE
VMTest => createNameRegistrator

### ISSUE THREAD

**Issue by romanman** [ethereum/tests#55]
2 questions: 

 + Why do you omit the address of a ~created~ contract:[`945304eb96065b2a98b57a48a06ae28d285a71b5`]
https://github.com/ethereum/tests/blob/develop/VMTests/vmSystemOperationsTest.json#L1501

 + Why the nonce of the creator doesn't increase: 
https://github.com/ethereum/tests/blob/develop/VMTests/vmSystemOperationsTest.json#L1532

**Comment by CJentzsch** [comment]
1. The to address (=destination) of a creation is always empty.

2. In the vm test we can bot even know if the creation was successfull because we do not execute the init code. The increment of the nonce is a task of the state abd is not done in vm test.

I admit, this are just definitions for the vm tests, because we do not execute calls and creates in vm test, instead we just make a "callcreate" entry.

**Comment by romanman** [comment]
@CJentzsch : thanks CJ, I will
align my testing structure that way.
