### ISSUE TITLE
Extend call_then_call_value_fail_then_returndatasize

### ISSUE THREAD

**Issue by chfast** [ethereum/tests#585]
The test call_then_call_value_fail_then_returndatasize checks interesting case where return data buffer should be cleared even if a call fails quickly by insufficient funds. The same case can happen for CALLCODE and CREATE but are not tested.

**Comment by winsvega** [comment]
testcases: 
(same as in the test but with CALLCODE/CREATE/CREATE2

* tr ->  contractA -> CALL contractB (return memory);   contractA continue:  -> { CALLCODE | CREATE | CREATE2 } to the same contract and fails (due to funds or subcall error) returns.   contractA continue: check the value of memory should be empty.
