### ISSUE TITLE
statetest: nonce maybe wrong

### ISSUE THREAD

**Issue by wanderer** [ethereum/tests#63]
this nonce maybe wrong https://github.com/ethereum/tests/blob/develop/StateTests/stSolidityTest.json#L226

I think it should be 2. The nonce gets incremented once for sending the transaction and once again for the creation of [2adc25665018aa1fe0e6bc666dac8fc2697ff9ba](https://github.com/ethereum/tests/blob/develop/StateTests/stSolidityTest.json#L216)

**Comment by CJentzsch** [comment]
The YP says: " nonce: A scalar value equal to the number of transactions
sent from this address or, in the case
of accounts with associated code, the number of
contract-creations made by this account". The "or" is important here. Sine this is a contract, the nonce only gets updated when it creates another contract. But the test case here will likely never happen. Because after creating a contract you dont know the secret key, only the public key. Only in a test we could create such a thing. So normally you will never receive a signed transaction from a contract with code.

**Comment by winsvega** [comment]
2adc25665018aa1fe0e6bc666dac8fc2697ff9ba is currentbase
acoount has tried to create contracts but this operation run out of gas
and as it was executing itself by a transaction, it's nonce incremented by 1
