### ISSUE TITLE
The recent tests changes

### ISSUE THREAD

**Issue by winsvega** [ethereum/tests#763]
**The recent tests changes:**
EIPS covered with **Berlin** test configuration (geth YOLOv2, YOLOv3)

**Update all:**
PR https://github.com/ethereum/tests/pull/723
PR https://github.com/ethereum/tests/pull/775

>**EIP2929** (https://eips.ethereum.org/EIPS/eip-2929) 
Gas cost increases for state access opcodes
PR https://github.com/ethereum/tests/pull/760
PR https://github.com/ethereum/tests/pull/756
PR https://github.com/ethereum/tests/pull/745

>~~**EIP2537** (https://eips.ethereum.org/EIPS/eip-2537)
Precompile for BLS12-381 curve operations
PR https://github.com/ethereum/tests/pull/713~~
REMOVED: https://github.com/ethereum/tests/pull/776

>**EIP2315** (https://eips.ethereum.org/EIPS/eip-2315)
Simple Subroutines for the EVM
PR https://github.com/ethereum/tests/pull/693
PR https://github.com/ethereum/tests/pull/685

>**EIP2565** (https://eips.ethereum.org/EIPS/eip-2565)
ModExp Gas Cost
existing test regeneration will test out the changes
PR: https://github.com/ethereum/tests/pull/775
PR: https://github.com/ethereum/tests/pull/779
PR: https://github.com/ethereum/tests/pull/777

>**EIP2718 - EIP2930** (https://eips.ethereum.org/EIPS/eip-2718, https://eips.ethereum.org/EIPS/eip-2930)
(Typed Transaction Envelope, Optional access lists)
New test format (access list test example): PR: https://github.com/ethereum/tests/pull/772/files
Access list tests PR: https://github.com/ethereum/tests/pull/774

>**VMTests rework under GeneralStateTests**
PR: https://github.com/ethereum/tests/pull/771

**Comment by holiman** [comment]
EIP 2565 (modexp repricing)
Looks like 2537 is not going to be included
EIP 2930  + 2817 (still being finalized)

**Comment by holiman** [comment]
Sorry, GH didn't update the page, so I didn't see your edits until after I posted

**Comment by winsvega** [comment]
moved to pre releases

**Comment by holgerd77** [comment]
Hi,
thanks so much for this, these new releases are really great! 😄 

One small suggestion: I think it would be better to not do pre-releases at all but just do everything as a normal release. I realized lately that for us as a user a "final" release has very much low relevance since we just update from release to release and at the same time it is unfortunate with the pre-releases that this leads to having this super-old `v7.0.0` release displayed on the main GitHub page as the latest release. This will likely confuse people.

![image](https://user-images.githubusercontent.com/931137/109481217-c71c8300-7a7c-11eb-9b66-b40327653dd9.png)

**Comment by holgerd77** [comment]
Ah, and as a side note: this suggestion is also influenced by the experiences from #692 where we (so you guys and me)were waiting for a final release for months, which made not so much sense since the clients needed to update the tests anyhow, being towards a "final" release or not.

So I guess it's not really worth to focus so much on final releases as I initially did, hardfork planning is often somewhat unpredictable and from my observation of the work here on the repo it is often hard or just not really possible to find a good  "sweet spot" for a final release.

This will likely be directly again the case with this planning for Berlin and London happening somewhat in parallel, so it might very well be the case here that we get into some repo state here where Berlin tests are not yet "finalized" but the first London tests need already to be merged in.
