### ISSUE TITLE
"Invalid" uncle seems to be valid

### ISSUE THREAD

**Issue by carver** [ethereum/tests#787]
This issue looks similar to: https://github.com/ethereum/tests/issues/694

I am testing py-evm using v7.0.1

The following test is asserting that if a block with timestamp 3001 and parent timestamp 2001 includes an uncle with timestamp of 1001, that it is invalid:
https://github.com/ethereum/tests/blob/v7.0.1/BlockchainTests/InvalidBlocks/bcUncleHeaderValidity/incorrectUncleTimestamp.json

Why would that be invalid? I also don't understand why a test like this would be limited to Istanbul+. I don't see any uncle-timestamp EIPs that were merged into Istanbul.

Looking at this diff:
`git diff v7.0.0-beta.1 v7.0.1 src/BlockchainTestsFiller/InvalidBlocks/bcUncleHeaderValidity/incorrectUncleTimestampFiller.json`, this seems to be the culprit:
```diff
                 "uncleHeaders" : [
                     {
-                       "populateFromBlock" : "1",
-                       "RelTimestamp" : "0"
+                        "populateFromBlock" : "1",
+                        "RelTimestampFromPopulateBlock" : "0"
                     }
                 ]
             }
```

I don't know how to read the [DSL for the tests](https://github.com/ethereum/tests/blob/v7.0.1/src/BlockchainTestsFiller/InvalidBlocks/bcUncleHeaderValidity/incorrectUncleTimestampFiller.json), but it looks to me like it was supposed to test what happens if the uncle header had the same timestamp as the including block. If that's true, then it seems like the block is not being generated as intended.

**Comment by winsvega** [comment]
there was this rule before transition tool: 
```Error importing raw rlp block: BlockHeader timestamp is less then it's parent block```

the question is is uncleHeader with timestamp less or equal then it's parent block is allowed. 

```
block1.timestamp = 1001
block2.timestamp = 2001
block3.timestamp = 3001
  with uncle.number = 2
         uncle.timestamp = 1001
```

so the uncle is rejected because it has number 2 and timestamp 1001 but there was already block number 1 and timestamp 1001. and the distance between blocks is violated.

**Comment by holiman** [comment]
The uncle is verified much like a regular header, meaning, 
- The parent (header@1) of the header (uncle@2), needs to be _before_ the header (uncle@2). 

From what @winsvega writes, it looks like that rule is violated, if indeed `block1` is parent of `uncle`, and `block1` and `uncle2` both have timestamp `1001`. 


> there was this rule before transition tool

The `evm t8n` has nothing to work with here. It's for state transitions, but this test concerns block validity, and there is no state transition. (A state transition: have pre-state, apply transactions, obtain post-state). 

Also, these tests cannot really be executed on hive, hive can test that a block imports correctly, but it's harder to test that a block correctly is rejected. 

I know I [previously](https://github.com/ethereum/tests/issues/694#issuecomment-636016240) said otherwise, but I do think (now) that the test is correct.

**Comment by holiman** [comment]
Yeah, geth rejects this on hive: https://hivetests.ethdevops.io/viewer.html?file=results/go-ethereum/client-1352abdf.log#L76

**Comment by carver** [comment]
:+1: Thanks for reviewing

**Comment by carver** [comment]
Ah, but this test should be valid against all old forks right, not just Istanbul-forward?

**Comment by holiman** [comment]
Yes, all
