### ISSUE TITLE
EIP1559 tests

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereum/tests#789]
It would be great to have EIP1559 tests. Especially if it is decided that we want EIP1559 in the London fork (see https://github.com/ethereum/pm/issues/254), we should get tests ASAP.

CC @lightclient 
@timbeiko 
@tkstanczak 
@abdelhamidbakhta

**Comment by jochem-brouwer** [comment]
These tests should also cover the transition from Berlin to London, so a network with a name like `BerlinToLondonAt5` should be added here.

**Comment by winsvega** [comment]
Ah thats the hottest discussion eip over there. 

https://www.reddit.com/r/ethereum/comments/lk1rjp/this_is_why_eip_1559_is_good_and_why_vitalik/?utm_medium=android_app&utm_source=share

**Comment by qbzzt** [comment]
Tests:

1. Check if EIP 1559 is running. Run a transaction, and see if any wei disappear. This can be a state test (with hardwired expected results) or a blockchain test with a program that looks at the balances.

2. Check what happens if we have a bunch of nearly empty blocks (`gas_target` >>> `gas_used`). The same transaction, with the same gas price, should give the coinbase more wei after such blocks because `base_fee_per_gas` gets lower when blocks are under utilized.

3. Check what happens if we have a bunch of overfull blocks (`gas_target` < `gas_used`). To do this, have a contract call that spends all of its gas (or almost all).

4. Create transactions of the new type (with `max_inclusion_fee_per_gas` and `max_free_per_gas`). See it is processed correctly, both in terms of how much it gives `coinbase` and the auction mechanism.

**Comment by timbeiko** [comment]
AIUI, @garyschulte is working on some tests, so he can chime in. For the scenarios above: 

> Run a transaction, and see if any wei disappear. 

I'm not sure how the testing framework is set up, but a stricter condition here would be that the amount burnt is `base_fee_per_gas` * `gas_used`. 

> Check what happens if we have a bunch of nearly empty blocks (gas_target >>> gas_used). The same transaction, with the same gas price, should give the coinbase more wei after such blocks because base_fee_per_gas gets lower when blocks are under utilized.

I'm not sure this will actually result in a higher reward to the coinbase. If the `base fee per gas` ends up below the `max fee per gas`, then at most the coinbase should get `max inclusion fee per gas`, but if the `base fee per gas` goes even farther below, then it will start "eating into" the `max fee per gas`. We should test that if possible. 

>Check what happens if we have a bunch of overfull blocks (gas_target < gas_used). To do this, have a contract call that spends all of its gas (or almost all).

Yeah, I think ideally we should drive the `base fee per gas` all the way to its minimum with empty blocks and then back up to a fairly high level with large calls. 

> Create transactions of the new type (with max_inclusion_fee_per_gas and max_free_per_gas). See it is processed correctly, both in terms of how much it gives coinbase and the auction mechanism.

Again, I'm not sure how the test repo is setup, but I guess we probably need to test all the combinations of pre-1559 vs. 1559 transactions, both with and without access lists.

**Comment by SuburbanDad** [comment]
> AIUI, @garyschulte is working on some tests, so he can chime in. For the scenarios above:

@qbzzt and I have conferred a bit about the 1559 tests.  I have a draft hackmd where I am describing the current state of reference tests, modeled after your 1559 status hackmd @timbeiko 

https://hackmd.io/@SduYUIHbT6a6DHUpikAcFQ/BJP9arcB_/%2FuID06YEhSj2uFzEviDIaJQ

I haven't focused too much on writing the test cases yet, since it seems that retesteth has a fair bit of work pending to support the 1559 spec.  Any feedback or suggestions are welcome.  

We may be able to move forward with general state tests ahead of 1559 support in retesteth, but I suspect the blockchain tests might need to wait until there is more clarity about how to support them with t8ntool.

**Comment by winsvega** [comment]
With t8ntool you can only process 1 block at a time. And no chain logic. If there is a specific chain logic for eip1559 please write it down so I can implement it in retesteth

Also need 1 client that support 1559 types in order to feed new type of tests to it

**Comment by garyschulte** [comment]
> Also need 1 client that support 1559 types in order to feed new type of tests to it

besu master supports 1559 transactions

**Comment by jochem-brouwer** [comment]
Quick trick to use all gas; just create a contract with the init code `0xFE` this asserts and consumes all gas.

Bugs on Aleut related to this EIP so far; (good test cases)

- Blocks where `gasUsed > gasTarget`
- Anything related to `GASPRICE` (GASPRICE PUSH1 0 SSTORE borked Aleut)

What's also interesting is that the spec does not state if it is OK to use a Transaction where the gasLimit of this transaction is higher than gasTarget. There is no special exception which states that you are not allowed to send a tx with a higher gasLimit than current gasTarget, so theoretically it *could* be possible to have a block with a single tx which spends twice the gas target.

**Comment by winsvega** [comment]
https://hackmd.io/NNforJS7SMmjJ1t6jA8pgQ
