### ISSUE TITLE
Call precompiled  contract by transaction

### ISSUE THREAD

**Issue by romanman** [ethereum/tests#82]
The call for `000...01 - 000...04` addresses strict from 
regular transaction is not tested yet , I can contribute several
examples, but don't sure in which section include them. @CJentzsch

**Comment by romanman** [comment]
e.g : http://pastebin.com/raw.php?i=KSq8uGMz

**Comment by CJentzsch** [comment]
Thanks for that important hint!
You can include those tests in https://github.com/ethereum/tests/blob/develop/StateTests/stPreCompiledContracts.json
or create your own file. Which is probably better, since this file could be overwritten now and then by the automatic filling of tests.
Even better, you include it in the cpp filler files (the same test, but without post, postStateRoot, logs and out section)  which are here : https://github.com/ethereum/cpp-ethereum/blob/develop/test/libethereum/StateTestsFiller/stPreCompiledContractsFiller.json

**Comment by romanman** [comment]
@CJentzsch : 

pushed that one: 
https://github.com/romanman/tests/commit/5f5851103db9cff1e2304cd273e17d92af2c5c7a

if all good will do pull request. 

what is the filler for ?

**Comment by CJentzsch** [comment]
Because back in the days the protocol changed often and because it dont't want to manually calculate the stateRoot I have filler files, which only define the "pre"-state, the envirnomnet and the transaction. Out of them the current clients creates the test using testeth (https://github.com/ethereum/tests/wiki/Using-Testeth)

**Comment by CJentzsch** [comment]
sure, make a PR, it looks good.
