### ISSUE TITLE
Is there any update on VMTests?

### ISSUE THREAD

**Issue by LeoNCKU** [ethereum/tests#827]
Dear all:
I found that some testsuite are not enough in VMTests. For example the opcode 0x10 LT instruction has only 4 testsuite (lt0.json, lt1.json, lt2.json, lt3.json), will the testsuite added more in the future?

**Comment by qbzzt** [comment]
The original VMTests are deprecated. Instead, we are going to work on the state tests that include the VMTests (https://github.com/ethereum/tests/tree/develop/GeneralStateTests/VMTests) because they can run with our automated tools.

In addition to the four tests in https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/VMTests/vmBitwiseLogicOperation/ltFiller.yml,
In https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/VMTests/vmArithmeticTest/twoOpsFiller.yml#L509 we have 48 tests that use LT with different parameters (plus additional ones spread over the file). 

Do you have any additional tests you think we should have? If so, please tell us and we'll write them.

**Comment by qbzzt** [comment]
@LeoNCKU , do you have additional tests? If not, may I close this ticket?

**Comment by LeoNCKU** [comment]
@qbzzt Sorry, I don't have. Thanks for fixing my problem.
